### ISSUE TITLE
Possibility to make everything a bit more compact

### ISSUE THREAD

**Issue by tdgroot** [nana-4/Flat-Plat#105]
Not a bug, just a question.

First off, I really like the theme, it looks great!

One thing that bothers me with every gnome theme in general, is that all the UI elements take up a lot of space. For example:

![image](https://cloud.githubusercontent.com/assets/1165302/23746302/bd6dc20a-04bb-11e7-823b-256a6193dd22.png)

Here are my questions:

- Am I missing the point around the big UI elements?
- Would it be doable to fork a theme and make all the elements compact?

**Comment by nana-4** [comment]
> Would it be doable to fork a theme and make all the elements compact?

Yes, of course. As written [here](https://github.com/nana-4/Flat-Plat#license), this theme is licensed under the GPL, so you can fork it freely.

> Am I missing the point around the big UI elements?

I'm not an expert of UI design, but what I can say are:

- As pointed out by **Fitts's law**, the bigger elements are easier to click than the small elements.

- Also, in **material design** or **flat design**, too small spaces often make it look poor.

---

By the way, the big margins of the menu separators in that screenshot is a **bug** of gnome-shell. Ideally the spaces should be close to the menu of GTK3 theme, but unfortunately it has not been achieved due to the bug.

P.S. The theme of your screenshot doesn't look like `-compact` version. Have you tried `Flat-Plat-compact` or `Flat-Plat-light-compact` yet?

**Comment by tdgroot** [comment]
Hey,

Thanks for your answer and the clarification.

I was running the Flat-Plat theme, but the compact versions look even better! I'm now using Flat-Plat-compact as GTK theme and Flat-Plat-light-compact as Shell theme, making my desktop environment look even better. 

Thanks again :)
