### ISSUE TITLE
How can I change lock screen icons and background image?

### ISSUE THREAD

**Issue by CNBLACK** [nana-4/Flat-Plat#111]
How to change lock screen icons and background image?

I applied your lock screen gdm shell theme, But I want to change shell icons, and lock screen background image.

**Comment by nana-4** [comment]
In order to change the icons on the lock screen, just change the **icon theme**. However, note that the icon theme is necessary to be located under `/usr/share/icons/`.

Changing the background image requires somewhat complicated work. After changed the background image, you need to generate a binary file with `glib-compile-resources` and replace it. The following is the simplest method:

1. Download the source files.

2. Go `src/gnome-shell/3.18/assets/` or `src/gnome-shell/3.18/assets-dark/` and replace the `noise-texture.svg` with your asset.

3. Replace the `noise-texture.svg` _string_ in the `gnome-shell*.css` and `gnome-shell-theme.gresource.xml`, according to your asset name.

4. Run `sudo ./install.sh` from the `Flat-Plat/` directory on the terminal.

5. Reinstall the re-generated `gnome-shell-theme.gresource` according to the [`README.md`](https://github.com/nana-4/Flat-Plat#gdm-locklogin-screen).

---

**IMPORTANT NOTE**: As written in the [`README.md`](https://github.com/nana-4/Flat-Plat#gdm-locklogin-screen), this work might be dangerous, so please do it carefully and at your own risk. ;)

**Comment by nana-4** [comment]
This [ArchWiki](https://wiki.archlinux.org/index.php/GDM#Log-in_screen_background_image) may also help you.

**Comment by nana-4** [comment]
Since there's no response, I'd like to close this.

**Comment by CNBLACK** [comment]
nope, I successfully to change background, but I can't change lockscreen statusbar icons... :/

**Comment by nana-4** [comment]
Are you talking about the icon on the top right? Or not?

![image](https://cloud.githubusercontent.com/assets/9556384/25654123/d9be0cea-302a-11e7-87a2-0950194fad09.png)

**Comment by CNBLACK** [comment]
yeah that icons!

**Comment by nana-4** [comment]
Hmm, then it should work with putting the icon theme into `/usr/share/icons`. If it's still not work, the following reasons are conceivable.

- The directory structure of the icon theme is incorrect.
- The permission of the icon theme is incorrect.
- You have been putting the icon theme with the same name into `~/.icons`, `~/.local/icons` or `~/.local/share/icons`.
- etc.

**Comment by nana-4** [comment]
In any case, it's not a problem of this theme.

So even if you can't change the icons, I will not be able to help you anymore, sorry. Because I'm not an expert of this. So please question it elsewhere.

I'd like to close this issue.
