### ISSUE TITLE
Huge border\shadow around terminal window

### ISSUE THREAD

**Issue by uniqby** [nana-4/Flat-Plat#112]
If you report a bug or ask a question, please include the following information as required:
- v20170323
- libgtk-3-0:amd64  3.22.11-0ubun amd64 
- Ubuntu 17.04
- Wayland

![2017-04-21 12-31-50](https://cloud.githubusercontent.com/assets/1488394/25271994/bd019842-268e-11e7-8e6f-96d72342eed5.png)

**Comment by nana-4** [comment]
I confirmed this on Ubuntu GNOME with Wayland, but it seems not to be a theme-related bug.

Did you carefully check the [contents](https://github.com/nana-4/Flat-Plat/issues/new) of [`ISSUE_TEMPLATE.md`](https://github.com/nana-4/Flat-Plat/blob/master/.github/ISSUE_TEMPLATE.md)? This bug also occurs with the default Adwaita.

However, since this did not occur on Fedora 25 and Arch Linux, I suppose it is a Ubuntu specific bug. Therefore it is better to report this bug in Ubuntu's issue tracker.

**Comment by nana-4** [comment]
It seems that this bug has already been reported here:
https://bugs.launchpad.net/ubuntu/+source/gnome-terminal/+bug/1650395
