### ISSUE TITLE
[Feature Request] Transparent top bar on the dark shell theme

### ISSUE THREAD

**Issue by RikuKawai** [nana-4/Flat-Plat#114]
As the title says, only Flat-Plat-Light offers the transparent top bar but this makes the drop down menus lightly coloured.

**Comment by nana-4** [comment]
I'm going to give the top bar transparency when the upstream `gnome-shell` resolves [this bug](https://bugzilla.gnome.org/show_bug.cgi?id=747163).

See also: https://material.io/guidelines/layout/structure.html#structure-system-bars
> By default, the color of the status or window bar is a darker shade of the app bar color.

As in material design guidelines, I want to use a darker shade of the title bar color to the top bar, so I'm not using a translucent color for now (except light variants).

However, since the light variant has both light and dark title bars, I'm using a neutral translucent black instead of an opaque color to the top bar.

**Comment by nana-4** [comment]
You can also use [Dynamic Panel Transparency](https://extensions.gnome.org/extension/1011/dynamic-panel-transparency/) until the upstream bug is resolved.

**Comment by TechnoSparks** [comment]
Or you may edit `./src/gnome-shell/3.18/sass` to change the dark variant to have that translucent look by a simple line change.

On line 46, change
```$panel_bg_color: if($titlebar == 'dark', $blue_grey_900, $bg_color);```
to
```$panel_bg_color: if($titlebar == 'dark', $bg_color, $bg_color);```

This relies on the previous declaration of `bg_color` on line 43. If you wish to fine tune the translucency, you can actually do that as well. Eg
```$panel_bg_color: if($titlebar == 'dark', rgba($red_900, 0.7), $bg_color);```

Re-parse SCSS and then reinstall the theme

**Comment by nana-4** [comment]
I made the top bar translucent (when the window is not maximized) for gnome-shell `3.26`.

So I'd like to close this issue.
