### ISSUE TITLE
Request: support Gnome 3.14

### ISSUE THREAD

**Issue by tonydiep** [nana-4/Flat-Plat#126]
__THANKS FOR GREAT THEME__
* Thank you so much for creating this great theme. 
* It is miles ahead of its competition in use-ability.

__REQUEST: SUPPORT GNOME 3.14__
* Some of us must use the stable, older, releases and are stuck on Gnome 3.14
* For those of us using production Centos and Redhat, __please consider supporting Gnome 3.14.__

**Comment by nana-4** [comment]
I'm sorry for the late reply.

Previously Flat-Plat supported `3.14` and `3.16` but now dropped because keep supporting many versions is so hard.

GTK+ `3.14` has been released three years ago and has many different specifications from the current **stable** version `3.22`. Therefore it is not easy to support `3.14` again, and honestly I do not want to devote much effort there. Sorry.

However, the last version for `3.14` is available. Here:
https://github.com/nana-4/Flat-Plat/releases/download/v3.14.20160921/Flat-Plat-3.14.20160921.tar.gz
