### ISSUE TITLE
Gtk2 application window shading incorrectly rendered on Hi-DPI screens

### ISSUE THREAD

**Issue by cthbleachbit** [nana-4/Flat-Plat#24]
This is the window border and shader on my Surface Pro 3 (12'' diagonal, 2160 x 1440 resolution and 216 pixels per inch). I've turned on Hi-DPI settings in gnome and clearly the shades are incorrectly rendered.
![screenshot from 2016-03-27 13-02-16](https://cloud.githubusercontent.com/assets/3353318/14063906/5ab1a484-f41c-11e5-8abd-302905a8b4fa.png)

This doesn't happen on my desktop 20'' 1600 x 900 monitor (92 pixels per inch).

**Comment by tista500** [comment]
@nana-4,

I'm not sure this issue was related to SSDs in backdrop state or not, but if we did NOT override the SSDs box-shadow with fake borders, 'truncated' normal state box-shadow appears around the SSD window in backdrop state. The truncation would be related to limited margin of GtkWindow, in your theming, equal to 8px (resize-gap area).:
```
diff -uNrad a/gtk-3.0/_common.scss b/gtk-3.0/_common.scss
--- a/gtk-3.0/_common.scss	2016-03-29 04:11:40.650009257 +0900
+++ b/gtk-3.0/_common.scss	2016-03-29 04:12:26.030009279 +0900
@@ -2228,7 +2228,7 @@
   }
   // server-side decorations as used by mutter
   &.ssd {
-    // box-shadow: 0 0 0 1px $borders_color; //just doing borders, wm draws actual shadows
+    box-shadow: 0 0 0 1px transparent; //just doing borders, wm draws actual shadows
   }
   &.csd {
     &.popup {
```
The transparent fake-border drawn with box-shadow may be safe for your theming, so could you please check whether this could help you guys. :)

Regards.

P.S 
I'm sorry if you had already started tracking down this issue.

**Comment by cthbleachbit** [comment]
@tista500 Your patch works. Why not start a pull request?

**Comment by cthbleachbit** [comment]
Sorry, I'm wrong on this.

All gtk2 applications don't get rendered as expected like rhythmbox in the picture above

But gtk3 applications are rendered correctly. For example, Nautilus
![screenshot from 2016-03-29 22-10-47](https://cloud.githubusercontent.com/assets/3353318/14110902/244a7b88-f5fb-11e5-9858-69c89a585ea0.png)

**Comment by tista500** [comment]
@cthbleachbit,

??
What are you talking about?
My suggestion is for Mutter. I'm not talking about Gtk+ version, but SSDs and CSDs. And it really doesn't matter whether Gtk+ version was 2.0 or 3.0 in this issue I suppose... Because all of Gtk+ 2.0 window-frames are handled by Mutter as SSDs in Gnome-Shell.

Regards.

**Comment by nana-4** [comment]
Sorry for the late reply. I'll fix it.

@tista500 Perfect! This was very helpful for me! Thanks for your advice. :)
