### ISSUE TITLE
Some controls don't follow Material Design guidelines

### ISSUE THREAD

**Issue by ricardopvz** [nana-4/Flat-Plat#59]
ComboBoxes and Entries shouldn't have shadows.
Check here: https://material.google.com/components/menus.html#menus-behavior
and here: https://material.google.com/components/text-fields.html#text-fields-input
They should be underlined with a gray color and underlined with the accent color when hovered or selected.
Adapta theme does it right.

**Comment by nana-4** [comment]
I know what you mean. BUT this is GTK theme, not Android theme. GNOME guidelines and components are not same with MD. I think that it is more important to bridge the gap between GNOME and MD than to follow MD guidelines perfectly. So I don't dare follow them in order to reduce the discomfort.

P.S.
Even in MD guidelines, entries on complex screen that have shadows.
Check here: https://material.google.com/components/bottom-navigation.html#bottom-navigation-behavior
