### ISSUE TITLE
[gnome-shell] Ellipsis placed on line middle

### ISSUE THREAD

**Issue by daltones** [nana-4/Flat-Plat#80]
* Distribution: Arch Linux
* Desktop environment: Gnome 3.20
* GTK+ 3 version: 3.20.6
* Flat-Plat version: git a786b0bc6d7df1553c26b9fae314f6a28145a7a9
* Screenshot(s):

![captura de tela de 2016-10-11 20-36-16](https://cloud.githubusercontent.com/assets/5603632/19292547/3cc3bbd8-8ff3-11e6-870a-457fe7f524bc.png)

![captura de tela de 2016-10-11 20-48-22](https://cloud.githubusercontent.com/assets/5603632/19292674/16ecc048-8ff4-11e6-8e1f-d3980b3bed90.png)

That's a problem with Gnome Shell Theme. Every ellipsis gets placed on the middle of the line. It's not a font problem and other themes like Arc displays ellipsis correctly.

**Comment by cthbleachbit** [comment]
![screenshot from 2016-10-11 20-16-29](https://cloud.githubusercontent.com/assets/3353318/19294140/a70294b4-8fef-11e6-93d7-c7641b902115.png)
Working fine here.

**Comment by cthbleachbit** [comment]
I guess that version is for gnome 3.22, and archlinux hasn't catch up with that yet.

**Comment by nana-4** [comment]
I believe this is a font problem. In GNOME Shell, we must specify font families to `gnome-shell.css`.
In order to work around this problem, you need to specify any font. Try to edit as following:

1. Open `gnome-shell.css` in `Flat-Plat/gnome-shell/` and move to line 26.
2. Add your any font in the beginning of the value as following.

  >   font-family: **your-font,** "M+ 1c", Roboto, Cantarell, Sans-Serif;
3. Reload the gnome-shell theme.

**Comment by daltones** [comment]
@nana-4 Thanks! You're right.

I had `ttf-mplus` installed but I was not using it as the interface font. And M+ 1c has that weird dots.

I thought that gnome-shell themes use the same font.
