### ISSUE TITLE
Question regarding newfound Budgie hate

### ISSUE THREAD

**Issue by ikeydoherty** [nana-4/Flat-Plat#95]
I have to ask, because this is raising a lot of eyebrows right now..

https://github.com/nana-4/Flat-Plat/commit/679199569926867eaa77c300811b798e330639b7

> Drop support for *damn* Budgie

https://github.com/nana-4/Flat-Plat/releases/tag/v20161227

> Boycott Budgie.

Seriously, what's the issue here?

**Comment by ikeydoherty** [comment]
P.S. if its something that _I_ can fix - then please just let me know. I've no issue in making life a bit easier for people :)

**Comment by nana-4** [comment]
Solus and Ubuntu Budgie **officially** support `Adapta` forked from this theme and ignore this _original_ theme. It sounds to me like that those devs say it’s not necessary to support Budgie in this theme. That's all.

I know I have no talent as a developer (or a designer), but their attitude disappointed me. So (honestly I was worried quite a bit, but) I decided to drop supporting Budgie with this theme.

**Comment by nana-4** [comment]
P.S. Adapta is better. So you don't need to do anything. Thank you.

**Comment by ikeydoherty** [comment]
I think you got this one a bit twisted. The only theme that Solus officially supports is Arc, as it is our default theme. If you're talking about themes available in our repos, then that's a completely different story. We only provide what has been requested by users.

However, there are quite a number of Solus/Budgie users of Flat-Plat, who install it locally and haven't requested it. I know this because I was told by one of them yesterday on IRC that you'd removed support for Budgie, and they were very shocked that you'd done this.

Back to the topic of "those devs". I'm the Budgie developer, and the Solus founder. There is only one person you listen to when it comes to matters of anything "official" in the context of Budgie, and that's me. So "those devs" you don't listen to, because it has nothing to do with Budgie itself.

> Those devs are trying to make Adapta the de facto standard
> but their attitude disappointed me

Lad, you need to look at the full picture. I hate material design. So I've no interest in making anything the "de facto standard". The only interest I have is in keeping my views of MD out of the way, and ensuring that Budgie users have a large and healthy choice for theming. To imply I would restrict that, is absurd.

**Comment by nana-4** [comment]
OK, first apologize for some misunderstanding.

Because I am not good at English, the phrase "de facto standard" was not an appropriate expression. I thought that nuance will transmit, but that was my mistake.

Previously "Ubuntu Budgie" was a confusing name "Budgie Remix" on the GitHub, so I misunderstood that the Budgie team is clearly involved it. e.g. [this site](http://linuxscoop.com/video/budgie-remix-16-04) seems to introduce that Budgie Remix is _created by the amazing team of developers from the Solus Project_.

The "healthy choice" is established on healthy fairness. But the "Budgie Remix" team abandoned it. And they robbed my motivation and energy to keep supporting Budgie. (It was my misunderstanding but) I understood that the Budgie team officially backed up the Adapta; just a fork. That is why I discontinued support Budgie on the theme.

I apologize for criticizing Solus/Budgie from my misunderstanding. And I updated the [release page](https://github.com/nana-4/Flat-Plat/releases/tag/v20161227).

---

P.S. Please forgive my poor English. I couldn't express a tenth of what I want to say because I don't have English proficiency.

**Comment by ikeydoherty** [comment]
I had a suspicion this might be the case. No apologies needed, you crack on and keep providing variety for people :D

**Comment by fossfreedom** [comment]
@nana-4 as project lead I'm more than a little surprised and disturb what I have read here.

Similar to Ikey - it is our users that have been requesting more theme support.  We similarly only officially support Arc. 

It is important to note that we have been looking at ways to make it easy for our users to install and most importantly keep up-to-date with upstream changes.

That is our only thoughts here - themes that have been chosen to be linked to by our "welcome application" are simply because they have PPA's which we can link to.  We constantly look out for more themes support and when they become available we intend to add those themes so that our users can choose and install via one click of a button.

We note you have an open issue about maintaining a ubuntu PPA (#44) - we sincerely hope one of your users of flat-plat will do this on your behalf.  Please let us know when a PPA becomes available and we will definitely and eagerly update our welcome application as soon as possible.

I hope that clarifies the position - we have not intentionally or otherwise said "support this theme ... but not that theme".  We are just linking to themes that are both easily installed and are easily maintained via Ubuntu's normal packaging mechanism.

**Comment by nana-4** [comment]
@fossfreedom I'm sorry for the very late reply. To be honest, I am not good at English, so I did not have the energy to write an objection in English. And it doesn't matter if you ignore this reply. Please think that this is like a soliloquy thing. Additionally, please forgive my poor English.

---

I think you don't seem to understand why I boycotted Ubuntu Budgie. I don't mean that I want Ubuntu Budgie to cover Flat-Plat.

I just want to say,
Why did you describe Adapta as "material design theme"? Are you kidding me???

I assert as the author of Flat-Plat, Adapta is obviously strongly influenced from Flat-Plat's code, design and ideas. So I think that recommending such a theme as the only "material design theme" is equivalent to saying like; Adapta is the only "material design theme" can be used regularly, and Flat-Plat is inferior theme worthless to try.

Eg, if you chose and expressed Paper as "material design theme", I would not feel anything uncomfortable. Because Flat-Plat and Paper have no particular relationship. But I cannot accept explaining Adapta, a fork, as the ONLY "material design theme".

If you treated Flat-Plat as inferior as an individual, I would not do anything. But if you do it as Ubuntu Budgie, I cannot help boycotting Ubuntu Budgie.

Maybe you didn't intend to disparage Flat-Plat. But it was a shame that an influential team like Ubuntu Budgie did something like that without consideration.

**Comment by fossfreedom** [comment]
@nana-4 please have a look here: https://github.com/UbuntuBudgie/budgie-welcome/blob/master/data/default.html

"Material Design (Adapta)" and "Material Design (Vimix)"

The author of Adapta describes Adapta as following a material design.  I'm not asserting his or any theme as the definitive material theme.  The quote is from the author himself.  I cannot and will not adjudicate in anyway which theme is material or not.

These are listed simply because they have PPAs associated with them and most importantly, those PPA's have a 17.04 archive.  We could not include "Material Design (Paper)" because the PPA does not have a 17.04 archive.

I really do not understand your assertion that Ubuntu Budgie treats Flat-Plat as inferior.  We cannot include the option "Material Design (Flat-Plat)" simply because there is no 17.04 PPA.  There is no slight here, no disparagement.  I cannot offer users Flat-Plat because there is no debian package for them to install.

I would like to reiterate again - we have only included links to themes that have 17.04 PPAs.

If you wish to talk to myself drop into our community chatroom.  More than happy to discuss further. https://gitter.im/ubuntubudgie/community

**Comment by nana-4** [comment]
@fossfreedom At least, until [this commit](https://github.com/UbuntuBudgie/budgie-welcome/commit/e0da609258e6269c56dea96bee2feb50ef429db5) it seems to have been introduced as "Material Design", not "Material Design (Adapta)". And it was before that that I decided to boycott.

> The quote is from the author himself. I cannot and will not adjudicate in anyway which theme is material or not.

So why did not you call it  "Adapta" or "adapta-gtk-theme"? Despite being officially recommended as "Material Design", is there anyone install Flat-Plat instead? That way of calling was not fair, I think. Therefore, supporting Budgie's theme became no longer make sense to me. It doesn't matter whether there is a PPA, imo.

Anyway, I didn't like being misunderstood, so I just wrote the objection. It's not because I'd like to make a detailed discussion. But thank you for inviting me.

**Comment by TechnoSparks** [comment]
I feel the need to hop in the conversation of this "closed" issue.

Dear nana-4, I understand your frustrations and the disappointment that you have regarding the issue. I have been in the same situation, although my final actions are different. 

I need to tell you something, as a user of your gorgeous theme, I for one finds your theme more pleasing and is well suited for making Linux beautiful.. In fact, as a personal stance, I find it better than the fork. Before your theme, I always used Arc, it is nice, but it's too flat. Your theme is a hero when I found it, like a blessing, as it is based on Material Design, whereas elevation plays quite a role. **I absolutely love Flat-Plat**.

I was scrolling through this repo's closed issues to see how committed you are with your work. I really love seeing committed developers.. It somewhat serves as an inspiration for me to keep developing, although I know I am just an amateur programmer. So, I stumbled upon this thread mentioning Budgie. I had disappointment when reading through it.

Budgie has been a desktop that is pulling my interest since the birth of Solus. It has a configurable Panel, it is based on GTK, and it does not focus on tablet-interface paradigm like Gnome. However, I don't want to use Solus, because of that it is a new OS, and it is not derived from Ubuntu. Since I have been using Ubuntu-based distro for a long time, I need the familiarity and would like to not going to go through another Distro's technicality again, especially package management.

So I have been keeping quite an eye to any possible Ubuntu-based distro making use of the Budgie desktop. This thread reveals that there is such a distro! But I am saddened, I cannot make the change of Distro because your theme cannot be used there. Its like, I am offered a huge dream, but something that I depend on forbids me from grasping that chance.

I know, I could just use Adapta, but nana-4, again, I emphasize, your theme is better in all ways.

As one of your faithful users, I would like to humbly request for you to enable support for Budgie again. Think of your users. They use your theme not for the sake of using, but because they like it. Creating a barrier like this will limit them from using what they love, and also ultimately making Linux distros less customisable and has less appearance options like people advertise them do. This is also the reason why I like Linux better than Windows. Your theme deserves to be recognised and used by people, and Material Design lovers like me and you.

I _may_ have misunderstood the actual reason why you boycott Ubuntu Budgie, but the action you took, which is to drop support, does prove an effect on behalf of your Budgie users, including me..

However, if you disagree and insist, I understand and will never ask again.

Sorry if this is offensive, and badly written. I do not intend for it to be like so. Like you, I don't speak English as a first language. My choice of words or tone selection could be wrong for some. I would like to stress that you are not obliged to accept my request, although I would be very, very happy if you do. :)

Warm regards.

**Comment by nana-4** [comment]
@TechnoSparks Firstly, I apologise for the delay in replying to you. And I appreciate your polite and kind reply.

Let me tell you the result first, I would like to support Budgie again in response to your request.

Originally, half of the reason why I stopped supporting Budgie was from my misunderstanding. And what you are saying makes sense.

To be honest, I suspected that Budgie's Flat-Plat users would be close to zero, and (not only Budgie but) it is hard to maintain many DEs, so I was hesitating to support it again.


By the way, one thing I would like to say to avoid misunderstandings is that "Creating a barrier" is by _them_, not by _me_. Boycotting Ubuntu Budgie by me was just a result. It is a response to unfair and not-free practices.

Finally, sorry for the rambling sentence and my terrible English.

Kind regards.

**Comment by TechnoSparks** [comment]
@nana-4 
I don't mind of any late replies. It is perfectly fine

Nothing can describe my excitement for the re-enabled support. I truly and immensely appreciate the action you took! You really made my morning when I read an email of your reply. Thank you so so much! I was anxious thinking that the email I received was going to be about you declining my request. It was a huge relief to read something different than expected.

I understand the difficulties of maintaining many DEs. You as a lone maintainer, I suggest for you to work on this wonderful theme at a comfortable pace with no pressure. This could ease down the difficulty you would normally have. *This is, just a suggestion.* I also may try to contribute in the future given enough knowledge of SCSS. 

> By the way, one thing I would like to say to avoid misunderstandings is that "Creating a barrier" is by them, not by me. Boycotting Ubuntu Budgie by me was just a result. It is a response to unfair and not-free practices.

You made it crystal clear. I understand, thanks for the clarification!

Again, I would like to thank you so much. 😄

Warm regards.

**Comment by nana-4** [comment]
@TechnoSparks 
I appreciate your thoughtfulness.

> I also may try to contribute in the future given enough knowledge of SCSS.

Of course the contribution of the code will be helpful, but I also would be happy even if you just try to fix documents written in my poor English. (e.g. `README.md`) 😄 

Anyway, Thank you for your understanding and the suggestion!
