### ISSUE TITLE
Blue variants

### ISSUE THREAD

**Issue by sebastianlacuesta** [nana-4/Flat-Plat#98]
It whould be nice to add some variants that use blue entirely, replacing every pink part. Really nice theme!

**Comment by bil-elmoussaoui** [comment]
@sebastianlacuesta You can get that easily as the theme was created using SASS.
Full steps : 
1 - `git clone https://github.com/nana-4/Flat-Plat/`
2 - Open a text editor and edit this file `_colors.scss` 
3 - Replace `$accent_color: $pink_A200;` with  `$accent_color: $light_blue_A200;` 
You can do that using `cd ./Flat-Plat && find . -type f -name "*.scss" -exec sed -i -e 's/$accent_color: $pink_A200;/$accent_color: $light_blue_A200;/g' {} \;`
4 - `sudo ./install.sh`
Note: the assets are rendered (and use png files) so you can't replace those colors until you use something like gimp to do that. 
@nana-4 Is there any way to get the svg icons of the assets? I can implement something to replace the colors on the Makefile if you wish that :)

**Comment by nana-4** [comment]
@sebastianlacuesta 
If every pink part (_accent color_) are made to have the similar color as _primary color_, it will be indistinguishable the appearance when the background is selected.

![image](https://cloud.githubusercontent.com/assets/9556384/21959551/e3f03868-db0d-11e6-8a5a-424a3e939f6b.png)

Of course it is possible to change the color of foreground widgets only when the background is selected, but I want to keep consistency and simplicity of the appearance, so colors are classified. Anyway, thanks. :)

**Comment by nana-4** [comment]
@bil-elmoussaoui Thanks for replying instead of me. :)

If just to replace the colors of the png assets, Gimp or something else are no needed. (but Inkscape needs to be installed. see for details: [`render-assets.sh`](https://github.com/nana-4/Flat-Plat/blob/master/src/gtk-3.0/gtk-common/render-assets.sh#L3))

Steps:

1. Open `src/gtk-2.0/assets.svg` and `src/gtk-3.0/gtk-common/assets.svg` with a text editor and move to [line 31](https://github.com/nana-4/Flat-Plat/blob/master/src/gtk-2.0/assets.svg?short_path=cd7dada#L31) and [line 76](https://github.com/nana-4/Flat-Plat/blob/master/src/gtk-3.0/gtk-common/assets.svg?short_path=ee0ff8c#L76).

2. Replace those `stop-color` values (`#FF4081`) with any color.

3. Delete all png assets. (Or it may be good only for specific pink assets.)

  ```
  rm -v Flat-Plat/src/{gtk-2.0,gtk-3.0/gtk-common}/assets/*.png
  ```

4. Render assets with `./render-assets.sh`.

  ```
  cd Flat-Plat/src/gtk-2.0 && ./render-assets.sh
  cd Flat-Plat/src/gtk-3.0/gtk-common && ./render-assets.sh
  ```

---

These svg images need to replace colors of `fill` individually.
- [`toggle-on.svg`](https://github.com/nana-4/Flat-Plat/blob/master/src/gnome-shell/3.18/assets/toggle-on.svg?short_path=89f7253#L2)
- [`more-results.svg`](https://github.com/nana-4/Flat-Plat/blob/master/src/gnome-shell/3.18/assets/more-results.svg?short_path=2825a57#L2)
- [`checkbox.svg`](https://github.com/nana-4/Flat-Plat/blob/master/src/gnome-shell/3.18/assets/checkbox.svg?short_path=10fcd70#L1)

And yeah, of course I would like to see your implementation if possible. :D

**Comment by bil-elmoussaoui** [comment]
I will pass my finals! once i'm done with that i will push that as a fix :)

**Comment by sebastianlacuesta** [comment]
@nana-4 Ouch! Good point on this.  My knowledge of color theory is near zero, and I couldn't ever think about this issue. Thanks for the answer!
